guillaumepotier/Parsley.js

src/parsley/abstract.js, src/parsley/ui.js
Simple simplifications to existing code (and thus no tests)
=> Simplifications

src/i18n/pt-br.js
URL is an acronym so it should be "um" and not "uma".
=> Fixed gender of URL

test/features/abstract.js, test/features/extra.js, test/features/field.js, test/features/form.js, test/features/multiple.js, test/features/parsley.js, test/features/pubsub.js, test/features/remote.js, test/features/ui.js, test/features/validator.js
Fix test comments and simplifications.
=> Trivial changes

src/parsley/validator.js
Increased from 4 to 24 - based on info derived from http://stackoverflow.com/a/22038535/2878424
=> updated TLD range for URL validator

CHANGELOG.md, doc/index.html, src/extra/plugin/remote.js, src/parsley/form.js, test/features/form.js, test/features/remote.js
I think this solves #813 and adds a useful event `form:submit.parsley`.
@guillaumepotier what do you think?
=> Clear cache

src/extra/plugin/remote.js, src/extra/validator/luhn.js, src/i18n/da.js, src/i18n/fi.js, src/i18n/ms_MY.extra.js, src/parsley/abstract.js, src/parsley/field.js, src/parsley/form.js, src/parsley/pubsub.js, src/parsley/ui.js, src/parsley/utils.js
http://api.jquery.com/jquery.noop/
=> Fix jshint error

src/i18n/de.js
add translations for messages
- mincheck
- maxcheck
- check
=> update german translation

doc/examples.html, doc/examples/customvalidator.html, doc/examples/events.html, doc/examples/multisteps.html, doc/examples/simple.html, doc/help.html, doc/index.html, src/parsley.js
Fixed a few small grammatical issues I noticed while reading through the documentation; I think these will help with clarity.
=> Grammatical improvements

.travis.yml, package.json, test/env/browserify.js
- try to fix browserify test suite
- new call for browserify / jQuery
- reverted jquery call w/ browserify
- still sh*t with browserify
- another try..
- try to deactivate travis browserify test
- last chance browserify try
- very last chance for our old friend browserify
- farewell travis browserify tests
=> farewell travis browserify tests

src/extra/validator/words.js
Words now can be separated by any not empty chain of '\s' symbols. Tabs, new line, spaces etc...
=> Words count func now uses "\s" as delimiter.

src/i18n/tr.js
* Minor fixes caused word-to-word translate
* Added semantic meanings
=> Turkish language file updated

src/parsley/validator_registry.js, test/unit/validator_registry.js
This is a fix for the issue I opened, issue number 1008.
Previous pull request got messed up by a code reorganization and it wasn't practical to try and fix, so made a new one.
=> Fix for - number alone passing validation

src/i18n/no.js
The sentences were, in my opinion, a too direct translation from English. This caused a few of the sentences to sound a bit odd.
=> Corrected some grammar in Norwegian translation

src/i18n/pl.js
Polish translation corrections.
=> Polish translation corrections

src/parsley/abstract.js
Removed periods to make all comments uniform
=> Cleaned up comments

src/i18n/eu.js
Added a new file for basque translations.
=> Added basque translations

src/i18n/ja.js
I felt something wrong in Japanese error message.
* This file includes misleading messages.
* Especially, `digit` message `"正しい桁数で入力してください。"` means `Please enter the correct number of digits`. It is wrong.
=> Update ja message

dist/i18n/es.extra.js
Added spanish translations to extra validators. Please, let me know if there is anything else needed for the PR.
=> Added spanish translations to extra validators

doc/examples/custom-validator-events.html, doc/examples/customvalidator.html, doc/examples/events.html, doc/examples/multisteps.html, doc/examples/simple.html, doc/help.html, doc/index.html, doc/tests.html, gulpfile.babel.js, test/runner.html
Part 1: https://github.com/guillaumepotier/Parsley.js/pull/1190
```
npm install htmlhint
./node_modules/.bin/htmlhint doc/ test/
```
=> Fix HTML errors. Part 2

dist/i18n/rs.js
Use the right Serbia 2-letter code confirmed by ISO
=> Serbia short code fix

dist/i18n/et.js, src/i18n/et.js
=> Added Estonian locals

doc/index.html
Just cleaning up what appear to be documentation mistakes.
=> Fix documentation mistakes

package.json
spmjs is RIP: https://github.com/spmjs/spm/commit/49e1757b99a76a69ddc10b53ed1d345c23817e36
=> Remove SPM support (outdated)

doc/annotated-source/field.html
A spelling mistake in documentation was fixed.
=> Fixed spelling mistake in documentation

README.md
Update links that automatically redirect from http to https
=> http to https

src/i18n/pl.js
=> Improved Polish translation

src/extra/validator/date.js
Date was checked before it was parsed.
=> Fix dateafternow/datebeforenow validators

dist/i18n/nl.extra.js
=> Update NL extra translation

src/i18n/is.js
Stumbled upon the badly translated error messages and replaced them.
=> fix: Locale - Icelandic translations

dist/i18n/cy.js
I've had the en v2.9.0 translated into Welsh (cy-GB)
=> Add Welsh (cy)
