guillaumepotier/Parsley.js

- src/parsley/field.js
- test/features/field.js
The check for a given `value` was oversimplified and didn't allow for `''`.
I didn't use the shorter form `null == value` because that isn't used anywhere else, but would you consider using that check (there and elsewhere) when looking for `undefined` or `null`?
From [this SO question](http://stackoverflow.com/a/21273362/8279)
> Being a more experienced JS developer now, I should note that using `if (variable == null)` is in fact the standard way to catch null and undefined simultaneously. When writing professional JS, it's taken for granted that the behavior is understood.
Also: http://stackoverflow.com/a/15992131/8279
> Fix this.value override to allow empty string

- CHANGELOG.md
- doc/index.html
- src/parsley/field.js
- test/features/field.js
This PR allows `option.value` to be a function. This is not available with the `data-featherlight-value` API, of course, only using the JS api.
I realize that the same effect can be obtained by listening to the `validate` event and setting the field's `value` directly, but I feel that giving this other intuitive possibility is good.
Based on 2.1
> Value function

- src/parsley.js
- src/parsley/ui.js
- test/features/parsley.js
- test/features/ui.js
TLDNR: This PR takes the approach that Parsley can’t and shouldn't filter fields at the constructor level and changes `init` to always return a `ParsleyForm` or `Parsley{Multiple}Field`, never a naked `Parsley`. It also adds error containers lazily (separate commit, could be split in a different PR).
Details:
In different circumstances, when calling `$.fn.parsley`, I get `Parsley` instances when I want `ParsleyField`.
I do not understand the idea behind return `Parsley` instances; it is definitely not useful for me, but maybe I'm missing something?
In any case, the current algorithm to decide to return a ParsleyField vs Parsley is deeply flawed. Ex:
<form data-parlsey-excluded=“nothing”><input type=“hidden”></form>
$(‘form').parsey()
$(‘input’).parsley() # => Parsley, should be …
> Fix field creation problems

- src/parsley/ui.js
- test/features/ui.js
Fix issue where failing fields were not revalidated after resetting:
- Reset _ui.failedOnce to false in reset()
- Relax check in reflow() to allow undefined or false
> Re-register failing field trigger after reset() [#710]

- src/i18n/no.js
Corrected Norwegian translation for alpanum from "alfranumerisk" to "alfanumerisk"
> Corrected alpanum translation

- src/parsley/ui.js
- test/features/ui.js
This is related to #843 which deals with the automatic change trigger but does not address the fact that when you call reset() any custom bindings added from the data-parsley-trigger attribute are lost.
> Re-bind custom triggers during a reset

- CHANGELOG.md
- doc/index.html
- src/parsley/field.js
- test/features/field.js
The new `whitespace` API handles actions on whitespace, which at the
moment consist of `trim` and `squish`.
- `trim`: removes leading and trailing whitespace characters from the
value.
- `squish`: replaces multiple sequential whitespace characters with a
single space, and then performs a `trim`.
This API can be used by the following data attribute-value pairs:
`data-parsley-whitespace=“trim”` or `data-parsley-whitespace=“squish”`
This PR deprecates the use of `data-parsley-trim-value=“true”`.
This PR replaces #853.
> Add new whitespace API

- src/wrap/append.js
That way it's passed to the define callback function of dependant modules as expected.
Fixes https://github.com/guillaumepotier/Parsley.js/issues/930
> Make AMD module in minified file return Parsley 

- CHANGELOG.md
- doc/index.html
- src/extra/plugin/remote.js
- src/parsley/abstract.js
- test/features/remote.js
This PR makes the `remote` validator much more flexible
1) Resurrect `field:ajaxoptions` event [#894]
2) Allow `{value}` in URL to be replaced by the value (instead of setting the data field). This is good for RESTful urls. This format follows RFC 6570 on URI templates.
@guillaumepotier I assume you're :+1: on these?
> Power remote

- Gruntfile.js
- package.json
For users of Parsley that load all of their dependencies, including jQuery, from RequireJS or Browserify, shims are not sufficient when loading the i18n files as dependencies in their current form because of the direct usage of jQuery (which may not be available when the code is run). This commit adds a build step which copies the i18n files from src into dist and wraps them in the UMD wrapper which is used for the main parsley file.
> provide UMD-wrapped i18n files

- doc/index.html
Corrected spelling of literal from 'litteral'
> Corrected typo

- src/parsley/validator_registry.js
When updating an existing validator, the result is not updated successfully.
> fix updateValidator bug

- doc/assets/docs.js
While having a constantly accurate bookmark without clicking is useful, the browser's history becomes unusable when the page gets even light usage.
> Don't update window hash on scroll (fixes #1149)

- .babelrc
"blacklist" is deprecated in Babel 6.
Source: http://babeljs.io/blog/2015/10/29/6.0.0#opt-in-plugins
> Removing .babelrc file since Babel 6 no longer allow "blacklist" option

- doc/annotated-source/field.html
- src/parsley/field.js
Problem
--------
_Since the 'range', 'min' and 'max' attributes have a different meaning when using them in a date html field, parsley will fail on processing these._
This is because Parsley expects a integer, where a date field expects a string.
Solution
--------
The min/max/range attributes have no validation purposes when used on a date field.They are only used for user experience (modifying the calender popup).
My solution exists of ignoring the min/max/range validator, when attributes are present on a date field.
> Added 'type' attribute check on range/min/max validator

- doc/about.html
- doc/download.html
- doc/examples.html
- doc/help.html
- doc/index.html
- doc/tests.html
- index.html
- `il, ul` on index.html - after 50d2f7b44bf0dae16b0560cfd8c91b56f4de9d1b
- `>` -> `&gt;` in `<code><pre>...</pre></code>`
- `<tt>` is deleted on HTML5
- Update navigation for extras and remote
- Remove duplicated id (`validators-list`)
- Fix not closed `<code>` and not opened `<tr>` tags
- Add `class="page-header"` for `h1#custom`
- Fix `getErrorsMessages` order cell.
...
Check by https://validator.w3.org/
> Fix HTML errors in docs

- .babelrc
- package.json
- src/parsley/constraint.js
The file `constants.js` has dependency on jquery only for using method `$.extend`, I change it to use vanilla method `Object.assign` instead.
I also took the time to apply `const` instead of `var`.
[Object.assign - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)
> Remove jquery dependency from constraint.js

- src/parsley/ui.js
It may happen that the classHandler is a string but the jQuery selector has length 0 because no elements are found.
That means we do not return and later try to use "call" on the string which results in a type error:
`Uncaught TypeError: classHandler.call is not a function`
I added a type check to fix that issue.
> Fixes error if classHandler is a string but $(classHandler) has length = 0

- package.json
JSPM needs the dependencies defined in a particular format. If this is not done one would need to define the dependencies manually. Also by not defining a jQuery version jspm will use the version that is currently being used in the said project.
> Defined dependencies for jspm

- dist/i18n/nl.js
E-mailadres is written in Dutch without space between 'e-mail' and 'adres'.
> Misspell 'e-mailadres'.

- src/parsley/ui.js
I suggest to you an improvement for people with disabilities.  These changes allow to create relationship between the field and its error. When the user is on a field with an error, the assistive technology informs the user of the error.
Maybe _updateError function must be change also.
[You can found more infromation on the website of the W3C](https://www.w3.org/WAI/tutorials/forms/notifications/).
Best regards
> Fix accessibility : relationship between field and error message

- package.json
The homepage key is also duplicate, not sure if that's intentional, but I doubt the license was
> Remove duplicate license

- doc/examples/simple.html
This commit replaces the 'Gender' radio button field on the 'Simple form example' page. There are a few reasons for this:
- Gender is not binary, so offering only choices for 'male' and 'female' doesn’t reflect users’ experience and reality.
- [Asking for users' gender is problematic and unnecessary](https://uxdesign.cc/designing-forms-for-gender-diversity-and-inclusion-d8194cf1f51) in most cases, so let’s discourage its use as a common field.
> Replace ‘Gender’ radio buttons in simple example.

- gulpfile.babel.js
- package.json
Hey hey @marcandre! I saw this gulpfile when getting you set up for Tidelift and figured I'd jump in to help align it with the current recommended patterns for gulp 4.
There's still a bunch of improvements that could be made, like streamlining the function names to avoid all the `displayName` annotations and cleaning up the docco task, but I think this is a great start.
> Update gulp patterns for v4

- dist/parsley.js
- doc/assets/spec-build.js
- src/parsley/remote.js
There is a small typo in dist/parsley.js, doc/assets/spec-build.js, src/parsley/remote.js.
Should read `query` rather than `querry`.
> docs: Fix simple typo, querry -> query
